language: ruby
rvm:
  - 2.4
services:
  - docker
branches:
  only:
  - develop
before_install:
  - docker pull antora/antora:2.3.0-alpha.2
  - docker run -it --rm --privileged --user=$UID:$UID -v $(pwd):/site -w="/site" antora/antora:2.3.0-alpha.2 --cache-dir=./_antora_cache --stacktrace playbook.yml
  - ls -la ./_antora_cache/content
  - rm -rf ./_antora_cache
  - docker ps -a
  - ls -la ./_site/documentation
  - touch ./_site/.nojekyll
script: rake travis
env:
  global:
  - secure: bLwcw0yZALDO8Z8Uy23rHb6ZEZotB1ikZP7wNR6xKC8jGkaBmEi3SAvfeMGbcUdew346Y0TsdDvF3GV8uGw4n+Xrri7fnBferZxjaX1M32lam8zRKNs0H1RDtv2yNFDkIzFEEAVy4h6foeaM9EON6+wOd9MWtrrcMq30CS1iuFTe6FM3pIoGF2rVlpYq7FceoPmj0mLGKxS8i6sVjKK+/F5JfsswquQvEEBNTpJT8hD6DFJcogbY9O/EpwyXkmwGMO1xVJ7mfgI4sl7ced1iYGcP1Vh1536ruP0jS8KfZxVuH6zRctRupxOM22Xa1jIqw6x+sUglvvpISwujLrEL1adPEuDYzawsixjyM196TI+7gzWUwld5YuWkorFD0IJwZ+E/zw13HlEY3ohi7B8C16kYxknkeDZDJm/6ZaCl5SuhsMZ5qQl/Lh9bc87JjQ/V9ecUqem8ycUFyWIURptRTFyfbpFyBdkiGt0VxsAGPyIfkZXCFs6I7fn5RQa0yNMQFm1kLIAi/damK1Jdg1eyK8pqY5E77sQg5NM3UFYoWFs+aD0DrarexLB1EAYc1RLlWOr4jsj3dan6Jx785U4mL0NU3uRuiDNNV+vuiTraqZujMCh3DShnj3upAlh1l7ushrTRW/wrfxOEH+qhYdrfULEHlNZ/BiL/aoaU0HD6a1o=
  - secure: JmdmzbfMqloMpYSzcbpoZynd9rtGrS0lDxRTjvybVorv3k9X4BWm8ygUo0gnqx6Q4RdA4t30YpXX3zVUrMyITmbSkqnvqBaWhEOpnyrZ6CvJKCt0AHwpnRGC33QNQW1eX5v04TQ2vLalcgAwYc12CX3/r3Q6NRxuixE8wkQoZ8hk+1DE3OqQon98qvPbjukvTC5zyFBjRzf0foqpOtk17lBx2vnNyTSLf3cyb+kDtrmkSZRr4WB53nyRua3BvaKMy7CutJOsFRD0HtI7BAaCFXoPIcyKKIOEIle3MnvEGdxERiAUHNMgWTH61nycf/2hXSMV3Q1WuBNF6+RDkL2wzq/TcMHRJX7Gq0fGdVkkFVRLcro3evUyDTk/AvHiSxEqi2lWkLAAD8bD99xJYGBevgt464T3YlTpLQrFqWFLTjEcZeC0fC7ymexQtw+Fjxi+innFArfmO0ds+9g0YS85bpTQ/R9UknecAIoNqHMDgUt/fj/qp13Ixgruv10WK0HjbyD7Rfw418e8G7h0Ue5HPKRtOEPgf2xouQiYUGeYxzbrRTZazSN09ZjGcBHvOUo2Vt4yHKx/qojGsZh0Sg77SR988d+O+1ZUKW9dt/hM07pW+h+khvnaqCjMcs3QZEQEJMdfO+gB/HIRCYwALgrWUqF4fd0EGC3O+RR87undbKY=
  - secure: XRUjgicbxnVX1XY8uakb3ZYJ338X9bcIrxY9ajcGQ0RZqlMEoa0SBk1Rx1X2ryGST02xLnm/glY8bJXV47dwxLC5fFA9XAV/JzhUP9jUgcR/tcFJEqJVjova0p4+GtH0F9AXN6BEnwF6Dbg7X9MJhz23qjtCNG+De5DjZO3MyvoWvJr8PElqg6asQPF0Xzp3cx11LtpMwWokaqzphnJzlelbAeVsDN4/d3EWlkvTUbwiejNASM//3fg6ZjP5UWdykP3b7T7TIekFMNlFgHnOriiE+u7TD1/1k3Q704v0E/laHIyc8HGNG9lgiX3QkJQp0ElKuy8sVQrQ3dR9SP1FekErHzwyIeLWpzKglybNKF/x5RvuBrXf6UzsybdmXCXoDA0qT5oV5+Mtr4EzTHdpHfHV3KSOkRH52XPoSagtkz6wpD/i6ttaqGXj12qnwyPGtuu4hI1slronbJSTA5YVc1uL6EIuWllEIaxUaarB5cGw2soeXm/Eef/LyrM7cHSgLPxdS+eUqz+CyoaDwNEukI8DiTa6IH0xj/HNnUdkt+wiA/zMigoV8XwgJPfMpeKsHaVgkwQN1nmkwX3Kf/qHxo7MtHn2S66ZnEQb3HgFIdy7r8QwglyUVA6pIlbPvR3uvAp5j/nbcLzENdtBkqf8qJEuVpumROtzutW+9qPAjg4=
