site:
  title: Debezium Documentation
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://www.debezium.io/documentation
  start_page: reference::index.adoc

content:
  sources:
    - url: https://github.com/debezium/debezium.git
      start_path: documentation
      branches:
        - '0.9'
        - '0.10'
        - master
      tags:
        - 'v1.0.0.Final'
        - 'v1.1.0.Alpha1'

ui:
  bundle:
    url: /site/_antora/ui-bundle.zip
    snapshot: true
  supplemental_files: /site/_antora/supplemental_ui
  output_dir: debezium-antora

runtime:
  fetch: true

output:
  dir: /site/_site/documentation

# These are global Antora attributes that will be used when building the Debezium documentation.
# These are placed here to avoid having to include an _attributes.adoc in every single asciidoc page.
# See https://github.com/debezium/debezium/pull/1152#issuecomment-568007275
#
# Ideally when changes are made to this section, you should also update playbook-author.yml to keep
# both playbook descriptor files in sync.
#
asciidoc:
  attributes:
    prodname: 'Debezium'
    assemblies: '../assemblies'
    modules: '../../modules'
    mysql-connector-plugin-download: 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.0.0.Final/debezium-connector-mysql-1.0.0.Final-plugin.tar.gz'
    mysql-version: '8.0'
    context: 'debezium'
    # because of how handlebars templates work with page.attributes, this must be prefixed with "page-"
    page-copyright-year: '2020'
