site:
  title: Debezium Documentation
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://www.debezium.io/documentation
  start_page: reference::index.adoc

content:
  sources:
    - url: /debezium
      start_path: documentation
      branches:
        # The development docs branch has been updated to be called '1.0'.
        # We should add a 0.10 branch and expose that version docs from there.  Until then, use 0.10.0.Final tag.
        # - 'development_docs'
        - '0.9'
        - '0.10'
      tags:
        - 'v1.0.0.Final'

ui:
  bundle:
    url: /site/_antora/ui-bundle.zip
    snapshot: true
  supplemental_files: /site/_antora/supplemental_ui
  output_dir: debezium-antora

runtime:
  fetch: true

output:
  dir: /site/_site/documentation

# See notes about this section in playbook.yml.
asciidoc:
  attributes:
    prodname: 'Debezium'
    assemblies: '../assemblies'
    modules: '../../modules'
    mysql-connector-plugin-download: 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.0.0.Final/debezium-connector-mysql-1.0.0.Final-plugin.tar.gz'
    mysql-version: '8.0'
    context: 'debezium'