site:
  title: Debezium Documentation
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://www.debezium.io/documentation
  start_page: reference::index.adoc

content:
  sources:
    - url: https://github.com/debezium/debezium.git
      start_path: documentation
      branches:
        # The development docs branch has been updated to be called '1.0'.
        # We should add a 0.10 branch and expose that version docs from there.  Until then, use 0.10.0.Final tag.
        # - 'development_docs'
        - 'master'
        - '0.9'
        - '0.10'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: /site/_antora/supplemental_ui
  output_dir: debezium-antora

runtime:
  fetch: true

output:
  dir: /site/_site/documentation
