site:
  title: Debezium Documentation
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://debezium.io/documentation
  start_page: reference::index.adoc

content:
  sources:
    - url: https://github.com/debezium/debezium.git
      start_path: documentation
      branches:
        - 'development_docs'
        - '0.9'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: /site/_antora/supplemental_ui
  output_dir: debezium-antora

runtime:
  fetch: true

output:
  dir: /site/_site/documentation
